{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-messaging",
    "version": "7.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-messaging-7.0.5.jar",
          "url": "spring-messaging-7.0.5.jar",
          "size": 613543,
          "sha512": "bede6acfa4ff6852e333f3a6e90794ccc3cf798100b99229c6ab86531fc4fb2a9592dfd3297abf43b44501532c114d6d4e44c577c702cdc977b2d0b6d6a95ffb",
          "sha256": "010a9933e387202f1f069fdb4fcae04af8a55f26279105e1f11ebe9d4acf2bf5",
          "sha1": "bbe3e67e2a92a31483339ef4172c185f9f45c9ce",
          "md5": "2857f85ff16dbdc32d06fad731321ed4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-messaging-7.0.5.jar",
          "url": "spring-messaging-7.0.5.jar",
          "size": 613543,
          "sha512": "bede6acfa4ff6852e333f3a6e90794ccc3cf798100b99229c6ab86531fc4fb2a9592dfd3297abf43b44501532c114d6d4e44c577c702cdc977b2d0b6d6a95ffb",
          "sha256": "010a9933e387202f1f069fdb4fcae04af8a55f26279105e1f11ebe9d4acf2bf5",
          "sha1": "bbe3e67e2a92a31483339ef4172c185f9f45c9ce",
          "md5": "2857f85ff16dbdc32d06fad731321ed4"
        }
      ]
    }
  ]
}
