{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry.instrumentation",
    "module": "opentelemetry-instrumentation-api",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.35.0"
          },
          "excludes": [
            {
              "group": "io.opentelemetry.instrumentation",
              "module": "opentelemetry-instrumentation-bom-alpha"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opentelemetry-instrumentation-api-2.1.0.jar",
          "url": "opentelemetry-instrumentation-api-2.1.0.jar",
          "size": 216952,
          "sha512": "f50d1f620fc4cb861c3dd93d50e24072db167ddab5ebca77cdaea9a69235e8852f9cbfbbedf15a938156b834a65731dea1f39540106dcaa993990b2475039e91",
          "sha256": "4f6ac1247c7372c103c23ef2594413418a496b114e13ef237031255a2d3ce361",
          "sha1": "ab63c535eb5f24c8a1d1585d702bf61e47092129",
          "md5": "f5c858e0a8feeaf15da035acb4679501"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-extension-incubator",
          "version": {
            "requires": "1.35.0-alpha"
          },
          "excludes": [
            {
              "group": "io.opentelemetry.instrumentation",
              "module": "opentelemetry-instrumentation-bom-alpha"
            }
          ]
        },
        {
          "group": "io.opentelemetry.semconv",
          "module": "opentelemetry-semconv",
          "version": {
            "requires": "1.23.1-alpha"
          },
          "excludes": [
            {
              "group": "io.opentelemetry.instrumentation",
              "module": "opentelemetry-instrumentation-bom-alpha"
            }
          ]
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.35.0"
          },
          "excludes": [
            {
              "group": "io.opentelemetry.instrumentation",
              "module": "opentelemetry-instrumentation-bom-alpha"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opentelemetry-instrumentation-api-2.1.0.jar",
          "url": "opentelemetry-instrumentation-api-2.1.0.jar",
          "size": 216952,
          "sha512": "f50d1f620fc4cb861c3dd93d50e24072db167ddab5ebca77cdaea9a69235e8852f9cbfbbedf15a938156b834a65731dea1f39540106dcaa993990b2475039e91",
          "sha256": "4f6ac1247c7372c103c23ef2594413418a496b114e13ef237031255a2d3ce361",
          "sha1": "ab63c535eb5f24c8a1d1585d702bf61e47092129",
          "md5": "f5c858e0a8feeaf15da035acb4679501"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-instrumentation-api-2.1.0-javadoc.jar",
          "url": "opentelemetry-instrumentation-api-2.1.0-javadoc.jar",
          "size": 393988,
          "sha512": "bb449eb43a0d3278320804437cba4c57c1181822565dae1bde8f7f33e98199ccabbc8f702137f9dbfa025920fc3bc375ce3695edffe9e5de42dcb984ab81c789",
          "sha256": "c05531084bb485f7a73313d019b0069297fb731984cb3d7f159258b1f2c84fb3",
          "sha1": "c8a49425749e0b372cc41fa7db5ad64091e464e9",
          "md5": "fefd2a9db067369759f8b7ed6769c20f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-instrumentation-api-2.1.0-sources.jar",
          "url": "opentelemetry-instrumentation-api-2.1.0-sources.jar",
          "size": 126920,
          "sha512": "1a071af91c9ee20ee881720703bd7055b4f0179b84378822732b48243ddb6092a1cd739c416f038a1255b8b884726e1f736d3ceba94d0733af55aefd5a823dd9",
          "sha256": "e0cc03c086549db4de9f0393829c8d5109c5d0b1a72aae63599bbca22d1229bd",
          "sha1": "cf02fda045d18e044bb11784363da82b469fd410",
          "md5": "c2fdb1b96b031deafba3e8ea03eaf6b1"
        }
      ]
    }
  ]
}
