{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-webflux",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-codec",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-webflux-4.0.3.jar",
          "url": "spring-boot-webflux-4.0.3.jar",
          "size": 149843,
          "sha512": "132b5abb0cb4356fe9974da54b391379b1ed8548a91003554578e3215b24d815befcc0b16e1af3acc117d819acf4d4577fbe7090a722a0c212d051e7821dcae9",
          "sha256": "fb35759056a1a07cb4aa18290da1ae0295872c37cf7eef80a9e1ce292472326a",
          "sha1": "344726f892c11419d3b9e94fa183db8c8d8d4fc2",
          "md5": "d73c739f33fdf75fe1b0083d478e6bcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-codec",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-webflux-4.0.3.jar",
          "url": "spring-boot-webflux-4.0.3.jar",
          "size": 149843,
          "sha512": "132b5abb0cb4356fe9974da54b391379b1ed8548a91003554578e3215b24d815befcc0b16e1af3acc117d819acf4d4577fbe7090a722a0c212d051e7821dcae9",
          "sha256": "fb35759056a1a07cb4aa18290da1ae0295872c37cf7eef80a9e1ce292472326a",
          "sha1": "344726f892c11419d3b9e94fa183db8c8d8d4fc2",
          "md5": "d73c739f33fdf75fe1b0083d478e6bcc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-webflux-4.0.3-javadoc.jar",
          "url": "spring-boot-webflux-4.0.3-javadoc.jar",
          "size": 295546,
          "sha512": "a69fbb1c8a92fca5c2cc61ba877dfa944199b1f6705b83b528ce79dccf3444242c662873c13eaa7c816dcd91e117913ef34aa122af6eb65bcc32158b0f333d44",
          "sha256": "26e55707b17873b0d68d9867349aeff71af9d11e94575b98292b37793f725def",
          "sha1": "dc206a2e974a48c54d6d9658a11abceb06d284a5",
          "md5": "8744d086f538c9adaf38d4c7a470c4a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-webflux-4.0.3-sources.jar",
          "url": "spring-boot-webflux-4.0.3-sources.jar",
          "size": 84409,
          "sha512": "2587d98198f36d43a313f6ea04834b4bb3b0fc3e24126b0dbf55726cb47e7a164575f8712cd12ef5e7b557cdd04c42729ed31cd9ee884ec739264af73131e871",
          "sha256": "4665593d60e12694df59356287792bf3a24b73ca0efcab418296c2e0f12c612a",
          "sha1": "c2c1476e3b55992f244598cc52e55d0e46f40e8c",
          "md5": "d01635fc3c6a3c1cb1826b8441584d88"
        }
      ]
    }
  ]
}
