{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-cbor",
    "version": "2.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-cbor-2.20.2.jar",
          "url": "jackson-dataformat-cbor-2.20.2.jar",
          "size": 73185,
          "sha512": "a8adcc385e04fb2b3c8a971aa5de882302165076cd29d943727669a5dc37038bf7b6fedda2ad4f0eebe3764610d1bc982f51c4c4b52966d583385ece7c068ee8",
          "sha256": "ad8e844f99297a4fe722927701f9b2c5e5bbefbc27fc3ce1736d0a0e9f42060e",
          "sha1": "c9a9275bedd0591c1939f3cacbe48006275ddc57",
          "md5": "b5a63223a464df98dbef4374656ef784"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-cbor-2.20.2.jar",
          "url": "jackson-dataformat-cbor-2.20.2.jar",
          "size": 73185,
          "sha512": "a8adcc385e04fb2b3c8a971aa5de882302165076cd29d943727669a5dc37038bf7b6fedda2ad4f0eebe3764610d1bc982f51c4c4b52966d583385ece7c068ee8",
          "sha256": "ad8e844f99297a4fe722927701f9b2c5e5bbefbc27fc3ce1736d0a0e9f42060e",
          "sha1": "c9a9275bedd0591c1939f3cacbe48006275ddc57",
          "md5": "b5a63223a464df98dbef4374656ef784"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-dataformat-cbor-2.20.2-javadoc.jar",
          "url": "jackson-dataformat-cbor-2.20.2-javadoc.jar",
          "size": 178268,
          "sha512": "8f432118942dec03e3414b6b98a7db2de88fdbf8458b793d2a098b243c740d4ee7589c6faf373ec65ac40d64f511efb74900e05aff99370864079229e0892438",
          "sha256": "6dc93fdcb56ed3f42c456c08a7251b31fa310066119136c2598bc41b193cebae",
          "sha1": "7195863378c4f0c4d24195f311e50a65b7026030",
          "md5": "2562e68cdd333e74619e6661a3dcf363"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-dataformat-cbor-2.20.2-sources.jar",
          "url": "jackson-dataformat-cbor-2.20.2-sources.jar",
          "size": 61988,
          "sha512": "498fdbb675e0e4fa1d230274fbe32b5fc7fa15a932312de2276630e1d589a4f8a5067891cf5a0f9a5a604e5a511ce92cc515f41c650fdf21a5f9652116e35011",
          "sha256": "6c73dc4b1745bdc6313b0914026bf41559fe616595afc17c56bc16a876938b16",
          "sha1": "c6c92829c0cd06ba9e0256be645ce4c2de664de5",
          "md5": "36867ce99c5dc87fb0a1ecdfb96f2bef"
        }
      ]
    }
  ]
}
