{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-websocket",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webmvc",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-websocket",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-websocket-4.0.3.jar",
          "url": "spring-boot-starter-websocket-4.0.3.jar",
          "size": 4755,
          "sha512": "9c9758531313387057dcf4baf8536c351c349b232ac18290a5c42ed2f271665b76089d01c36d3535697872738b4f07bd84192272e49ebda0453a7a57652aa1d2",
          "sha256": "d5a3b051c8321a95ec61660ca6cd7341ee3618ac8c978191f8b2332d4a3556f6",
          "sha1": "3647be0e19ec6c58e0e077bf9924bf2f112682dd",
          "md5": "f201cb05528efd4b072d3b6024146fbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webmvc",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-websocket",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-websocket-4.0.3.jar",
          "url": "spring-boot-starter-websocket-4.0.3.jar",
          "size": 4755,
          "sha512": "9c9758531313387057dcf4baf8536c351c349b232ac18290a5c42ed2f271665b76089d01c36d3535697872738b4f07bd84192272e49ebda0453a7a57652aa1d2",
          "sha256": "d5a3b051c8321a95ec61660ca6cd7341ee3618ac8c978191f8b2332d4a3556f6",
          "sha1": "3647be0e19ec6c58e0e077bf9924bf2f112682dd",
          "md5": "f201cb05528efd4b072d3b6024146fbc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-websocket-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-websocket-4.0.3-javadoc.jar",
          "size": 4755,
          "sha512": "9c9758531313387057dcf4baf8536c351c349b232ac18290a5c42ed2f271665b76089d01c36d3535697872738b4f07bd84192272e49ebda0453a7a57652aa1d2",
          "sha256": "d5a3b051c8321a95ec61660ca6cd7341ee3618ac8c978191f8b2332d4a3556f6",
          "sha1": "3647be0e19ec6c58e0e077bf9924bf2f112682dd",
          "md5": "f201cb05528efd4b072d3b6024146fbc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-websocket-4.0.3-sources.jar",
          "url": "spring-boot-starter-websocket-4.0.3-sources.jar",
          "size": 4755,
          "sha512": "9c9758531313387057dcf4baf8536c351c349b232ac18290a5c42ed2f271665b76089d01c36d3535697872738b4f07bd84192272e49ebda0453a7a57652aa1d2",
          "sha256": "d5a3b051c8321a95ec61660ca6cd7341ee3618ac8c978191f8b2332d4a3556f6",
          "sha1": "3647be0e19ec6c58e0e077bf9924bf2f112682dd",
          "md5": "f201cb05528efd4b072d3b6024146fbc"
        }
      ]
    }
  ]
}
