{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yubico",
    "module": "yubico-util",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.yubico",
          "module": "webauthn-server-parent",
          "version": {
            "requires": "2.8.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "yubico-util-2.8.1.jar",
          "url": "yubico-util-2.8.1.jar",
          "size": 26702,
          "sha512": "ce27ba853a6238f09773a1c66c9c977b3deada05ee01697b4daf8bdec01ab5c292e961fe791a2c004ff3b43fbcbef4ff6023c6ee0879f366adae0373e370e8c8",
          "sha256": "b2f326cb93fd94419d83cec6a30f6128a8459d0ea4f16bd3cb2e1ab1259577e3",
          "sha1": "770d2688aef2f11ddc2f88b7f0e476a8f9e7e81e",
          "md5": "3549becf7a24f1ecfaa2ff601011fa97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-cbor"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "com.upokecenter",
          "module": "cbor"
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api"
        },
        {
          "group": "com.yubico",
          "module": "webauthn-server-parent",
          "version": {
            "requires": "2.8.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "yubico-util-2.8.1.jar",
          "url": "yubico-util-2.8.1.jar",
          "size": 26702,
          "sha512": "ce27ba853a6238f09773a1c66c9c977b3deada05ee01697b4daf8bdec01ab5c292e961fe791a2c004ff3b43fbcbef4ff6023c6ee0879f366adae0373e370e8c8",
          "sha256": "b2f326cb93fd94419d83cec6a30f6128a8459d0ea4f16bd3cb2e1ab1259577e3",
          "sha1": "770d2688aef2f11ddc2f88b7f0e476a8f9e7e81e",
          "md5": "3549becf7a24f1ecfaa2ff601011fa97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yubico-util-2.8.1-javadoc.jar",
          "url": "yubico-util-2.8.1-javadoc.jar",
          "size": 126628,
          "sha512": "a9a82d42720a3c144fc2ade2cb93297d900771df800f2ab8819d267322dffb1434bda4940cdea56ebd9e02d5c0aaaaf71792ddfc974d5727dfd1e903f2ffb8d3",
          "sha256": "90bee5e7701e5602bf40272cae6d63357c9bbe5ac8126ecf42d46ca28f2323a4",
          "sha1": "e34e41d07d704620b75e1a8bc2fd258fa08fb481",
          "md5": "382509da495f52cbf9968d215fd8a5ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yubico-util-2.8.1-sources.jar",
          "url": "yubico-util-2.8.1-sources.jar",
          "size": 17614,
          "sha512": "33249a42a9f271c8684bdaa752d90da550bd8966f3d3fa8697c2a891482525e33dca550a1e478ad64358c9fb2b47b0872e0aaf074e374e4519b0438326615752",
          "sha256": "832e9e74422a4e0364e4478e95ff456416ed318a137bb17dc0a747ed8ebac325",
          "sha1": "21e9f37bb5e0fba5f29aac24ef5329e5244c035c",
          "md5": "b3df8af38675e8688350837ce8522011"
        }
      ]
    }
  ]
}
