{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yubico",
    "module": "webauthn-server-core",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.yubico",
          "module": "webauthn-server-parent",
          "version": {
            "requires": "2.8.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "webauthn-server-core-2.8.1.jar",
          "url": "webauthn-server-core-2.8.1.jar",
          "size": 426809,
          "sha512": "f86515469de71771d4b9d9c44ad2c57a8a4638545381ceaeae9b6b9ccccc0cab41d009ff4e23f53e5865ae907377db326d977a8048884c60edc3974b3b247ad3",
          "sha256": "e8b7ba0db2e6e87d0d06f519a35b9ec65b9f15242972e45c2a063834a2c25bfb",
          "sha1": "6399ca969cff2b3114e62308b035438e2a9b57b2",
          "md5": "74afb00d54e86d1cc840a4518668238d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.yubico",
          "module": "yubico-util",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "com.google.guava",
          "module": "guava"
        },
        {
          "group": "com.upokecenter",
          "module": "cbor"
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5"
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api"
        },
        {
          "group": "com.yubico",
          "module": "webauthn-server-parent",
          "version": {
            "requires": "2.8.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "webauthn-server-core-2.8.1.jar",
          "url": "webauthn-server-core-2.8.1.jar",
          "size": 426809,
          "sha512": "f86515469de71771d4b9d9c44ad2c57a8a4638545381ceaeae9b6b9ccccc0cab41d009ff4e23f53e5865ae907377db326d977a8048884c60edc3974b3b247ad3",
          "sha256": "e8b7ba0db2e6e87d0d06f519a35b9ec65b9f15242972e45c2a063834a2c25bfb",
          "sha1": "6399ca969cff2b3114e62308b035438e2a9b57b2",
          "md5": "74afb00d54e86d1cc840a4518668238d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webauthn-server-core-2.8.1-javadoc.jar",
          "url": "webauthn-server-core-2.8.1-javadoc.jar",
          "size": 704591,
          "sha512": "9ab3aa27b0f155433516f31c81043e307db5a0445993d498ad27bed243b77980870129be18f940dadddfa3cffb26f316c623f2b34d0498aecb9beface49d86e0",
          "sha256": "461fdeefeb151e196014f2f316f9c2358d01de07bda0c1a10329ad37c9d62e9e",
          "sha1": "fdc0487f926ac485f0ae2d838dff7473a8ae7713",
          "md5": "2e8557b80671c5a2fc1ce3ac3338f5b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webauthn-server-core-2.8.1-sources.jar",
          "url": "webauthn-server-core-2.8.1-sources.jar",
          "size": 219128,
          "sha512": "dce65c5e198cd00adc225bf3f2f873276ef3246d3fda00a9802cae3c368a62c4191d66f67f6eaa68ac4216e1f14e86b272b95c7221042966ec9c2bc35ab83ac0",
          "sha256": "51de620c71038be77f3e98ff4fab2b08d03cb902b77626d653f70928995c1ed2",
          "sha1": "2dafb2bbe0abf4f1b55b678921c6f1dd03ed4d12",
          "md5": "0afff88d367e25ec64bcbb62a94714d0"
        }
      ]
    }
  ]
}
