{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-extension-incubator",
    "version": "1.35.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.35.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-extension-incubator-1.35.0-alpha.jar",
          "url": "opentelemetry-extension-incubator-1.35.0-alpha.jar",
          "size": 33059,
          "sha512": "b61451eca738bb39b000abe018c91ac750e191d1995faf320204a8496495724981039c9bae87ac1569a98a36fa48bd405f2f36b7bc1dcaa7808c387c1dd05175",
          "sha256": "5ca38a9ecdf2c93183069dae1d7d76ec12e9cf4feb3c2209d04566e82fc4df3c",
          "sha1": "72720d7880110d02aad6d69066cc0311c568f17d",
          "md5": "6920f457f74863c96f880a2aadc44fbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.35.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-extension-incubator-1.35.0-alpha.jar",
          "url": "opentelemetry-extension-incubator-1.35.0-alpha.jar",
          "size": 33059,
          "sha512": "b61451eca738bb39b000abe018c91ac750e191d1995faf320204a8496495724981039c9bae87ac1569a98a36fa48bd405f2f36b7bc1dcaa7808c387c1dd05175",
          "sha256": "5ca38a9ecdf2c93183069dae1d7d76ec12e9cf4feb3c2209d04566e82fc4df3c",
          "sha1": "72720d7880110d02aad6d69066cc0311c568f17d",
          "md5": "6920f457f74863c96f880a2aadc44fbe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-extension-incubator-1.35.0-alpha-javadoc.jar",
          "url": "opentelemetry-extension-incubator-1.35.0-alpha-javadoc.jar",
          "size": 153144,
          "sha512": "99321297183d73567ea5a7651c6526efe24e8eb9d6611a5c9d6facbc311058e1ffb8fe5115f4f55dd30ccd8485b50f73949afdbeeaf35581c8e141f1942c0ec0",
          "sha256": "ae17319f67aa92215db35ea1f61014ffc9f55750c938b00604b43c3f7ba2c801",
          "sha1": "35c6928c065c3ca84005949087326a396daf1195",
          "md5": "629048f6cfe837800c39d54821e58ba8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-extension-incubator-1.35.0-alpha-sources.jar",
          "url": "opentelemetry-extension-incubator-1.35.0-alpha-sources.jar",
          "size": 23640,
          "sha512": "d09f6924ef373e4830aba37eac7123ca382140e812f8aef04cfb3beb343cb5295437c5ef0f5058185a74a01a6215af72ade436ca0a7c2cf5eeee71ee1d72423c",
          "sha256": "2469ad678701e0871b39288de539915afa5d0f7c4c266d0f464677fec88fa3d1",
          "sha1": "ab989206692293ff1c5736eaef8e20668537003f",
          "md5": "ac12ff9e226fa21879b3127826b35970"
        }
      ]
    }
  ]
}
