{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-reactor",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-reactor-4.0.3.jar",
          "url": "spring-boot-reactor-4.0.3.jar",
          "size": 11968,
          "sha512": "08f5ac6a168d7477ad7c32cc96343ad1fcaae66fbc4c0f0a709ef001d651634a3c7f2689b36c37c60475e4cb80869fd5e43d9c8d226f9db2d47603e1f584fa3f",
          "sha256": "84e4cbc8612774ea172509cfe15e502da8f55e27148267e659f586077ad2d50b",
          "sha1": "e3aff14ed945794bf366a0d2ae82ab99396e617d",
          "md5": "7ee4aa99c4b26efeddb9cf3445791dde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-reactor-4.0.3.jar",
          "url": "spring-boot-reactor-4.0.3.jar",
          "size": 11968,
          "sha512": "08f5ac6a168d7477ad7c32cc96343ad1fcaae66fbc4c0f0a709ef001d651634a3c7f2689b36c37c60475e4cb80869fd5e43d9c8d226f9db2d47603e1f584fa3f",
          "sha256": "84e4cbc8612774ea172509cfe15e502da8f55e27148267e659f586077ad2d50b",
          "sha1": "e3aff14ed945794bf366a0d2ae82ab99396e617d",
          "md5": "7ee4aa99c4b26efeddb9cf3445791dde"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-reactor-4.0.3-javadoc.jar",
          "url": "spring-boot-reactor-4.0.3-javadoc.jar",
          "size": 121982,
          "sha512": "00184f085d97ec3723a5b4713cd810612d0bf0936fe21ec4ef1c9f22043712ba8e22fd5ca91c38cb2765c56e54583f09b9e67ddc9f52160bb8a35a6a57cd55bb",
          "sha256": "d13c11fff46feae2ce8f617a2cbbb338b97c7e29618fbb025ddaba95fc1f7a8a",
          "sha1": "bc8c4ea7ce86d4a5cbda4e98955540bf23c52535",
          "md5": "b8a52782b82bbb3127f8b534d2e22ce5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-reactor-4.0.3-sources.jar",
          "url": "spring-boot-reactor-4.0.3-sources.jar",
          "size": 10936,
          "sha512": "5a2707feef88e8afb07b3c5d311340b280182c88dec39b31a470948e2f90d62c72b8f4f6f0749a0ec9d2bdf140f94ff95c13824e10d507209209447979ecb948",
          "sha256": "1af059c3457d3fc33cd001c53ad533f379b20d46785ce5f180ba4dc05c5d91c0",
          "sha1": "cc3dd0339b8a5c590ab8dd4000af65ea01da6e59",
          "md5": "53e7a24e0b4961a07d1cb4e60bdde4d3"
        }
      ]
    }
  ]
}
