{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webflux",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-4.0.3.jar",
          "url": "spring-boot-starter-webflux-4.0.3.jar",
          "size": 4756,
          "sha512": "2ec0e85cee2864617813c46b3c7ca44124ff86321799df1476c3c88929d7b5c47c09321231ba5f5262153cdfacdda835273513deddc03c71262a72ded5c1378f",
          "sha256": "3890c2ac17f4b21c7462b812d1d70a56bbea31119e261529e589363ad83f7490",
          "sha1": "37a3582c3c258493eb301ec6225d9d17bb33e950",
          "md5": "e03c99ea784abe61951c191ecac84712"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-4.0.3.jar",
          "url": "spring-boot-starter-webflux-4.0.3.jar",
          "size": 4756,
          "sha512": "2ec0e85cee2864617813c46b3c7ca44124ff86321799df1476c3c88929d7b5c47c09321231ba5f5262153cdfacdda835273513deddc03c71262a72ded5c1378f",
          "sha256": "3890c2ac17f4b21c7462b812d1d70a56bbea31119e261529e589363ad83f7490",
          "sha1": "37a3582c3c258493eb301ec6225d9d17bb33e950",
          "md5": "e03c99ea784abe61951c191ecac84712"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-webflux-4.0.3-javadoc.jar",
          "size": 4756,
          "sha512": "2ec0e85cee2864617813c46b3c7ca44124ff86321799df1476c3c88929d7b5c47c09321231ba5f5262153cdfacdda835273513deddc03c71262a72ded5c1378f",
          "sha256": "3890c2ac17f4b21c7462b812d1d70a56bbea31119e261529e589363ad83f7490",
          "sha1": "37a3582c3c258493eb301ec6225d9d17bb33e950",
          "md5": "e03c99ea784abe61951c191ecac84712"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-4.0.3-sources.jar",
          "url": "spring-boot-starter-webflux-4.0.3-sources.jar",
          "size": 4756,
          "sha512": "2ec0e85cee2864617813c46b3c7ca44124ff86321799df1476c3c88929d7b5c47c09321231ba5f5262153cdfacdda835273513deddc03c71262a72ded5c1378f",
          "sha256": "3890c2ac17f4b21c7462b812d1d70a56bbea31119e261529e589363ad83f7490",
          "sha1": "37a3582c3c258493eb301ec6225d9d17bb33e950",
          "md5": "e03c99ea784abe61951c191ecac84712"
        }
      ]
    }
  ]
}
