{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-http-codec",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-http-codec-4.0.3.jar",
          "url": "spring-boot-http-codec-4.0.3.jar",
          "size": 20039,
          "sha512": "ba28650965939a50a122cbe54ad08b3b1bb93645e7290c9a5d03ca731bc3dfbb9ffc70583bc38d6cae982e952f3ff63c2893b55db59692cd1d98a662a5edc2a7",
          "sha256": "7a6c986fe540681d838e527c08e8db3f47e8ffd7608816a139f3b3bfd0cbc381",
          "sha1": "6f6ce2f0cbf72cfbd7bb5cbcff7a6e432cf3fa8f",
          "md5": "5bee5f0b7e7047cba19334655bc4e42e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-http-codec-4.0.3.jar",
          "url": "spring-boot-http-codec-4.0.3.jar",
          "size": 20039,
          "sha512": "ba28650965939a50a122cbe54ad08b3b1bb93645e7290c9a5d03ca731bc3dfbb9ffc70583bc38d6cae982e952f3ff63c2893b55db59692cd1d98a662a5edc2a7",
          "sha256": "7a6c986fe540681d838e527c08e8db3f47e8ffd7608816a139f3b3bfd0cbc381",
          "sha1": "6f6ce2f0cbf72cfbd7bb5cbcff7a6e432cf3fa8f",
          "md5": "5bee5f0b7e7047cba19334655bc4e42e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-http-codec-4.0.3-javadoc.jar",
          "url": "spring-boot-http-codec-4.0.3-javadoc.jar",
          "size": 117340,
          "sha512": "755f6fd13dd8341a7811e9e44bec4502265566085ac7ad15f0a342b50fa0e308df7094166a17a7f35f26426c995b3737948d85d7381e6780d4e99bd255493e15",
          "sha256": "d13d037b74bc811d8bb749295e8b9b72d6bd0857c2ed3ed3097283d69840e5ef",
          "sha1": "4845835fcd973d63bbf949f64e109f2192968ada",
          "md5": "caa8cb5e774b594dab3436bc7b0f06a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-http-codec-4.0.3-sources.jar",
          "url": "spring-boot-http-codec-4.0.3-sources.jar",
          "size": 11702,
          "sha512": "babff7805198b0a33708949e8c94175a1cb97c8679f544e4614059bbd0c275fcdd0d802cb5e22c83e00a94b20172229db03d2f2073de29f6ed29a4d0f16daa74",
          "sha256": "d0270eef3a55891231ea093e58418e25e77bfd93929d00f97d84010da14568ad",
          "sha1": "7ab3baee106bb29add809eec7e418d95ddb1ef3d",
          "md5": "dddcc8cd0fec978ca4f31305de7b7def"
        }
      ]
    }
  ]
}
